version: '3.9'
services: 
  postgres:
    image: postgres:17-alpine
    container_name: postgres_verixa
    environment:
      # - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=verixa
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - verixa_postgres_data:/var/lib/postgresql/data

volumes:
  verixa_postgres_data: